### PR TITLE
kubernetes-sigs --> sigs.k8s.io

### PR DESCRIPTION
**Pull request by sanchezl**
`github.com/kubernetes-sigs/*` -> `sigs.k8s.io/*`

### CODE REVIEW

**Comment by sanchezl** [comment]
/hold

This will be cleaner after a switch to `go.mod`.

**Comment by caesarxuchao** [comment]
Why do we need this change?

**Comment by sanchezl** [comment]
> Why do we need this change?

It was pointed out to me that that is the appropriate vanity import path for Kubernetes SIG modules/packages.

**Comment by caesarxuchao** [comment]
/lgtm
approve

**Pull request merged**
