### PR TITLE
bump to Kubernetes 1.20.0-beta.2

### PR DESCRIPTION
**Pull request by roycaihw**
This allows us to use the StorageVersion API.

Note that the first three commits are from https://github.com/kubernetes-sigs/kube-storage-version-migrator/pull/79. And we still cannot get rid of klog/v1 in `go.sum` because the latest `sigs.k8s.io/controller-tools` (v0.4.1) still uses [Kubernetes 1.18](https://github.com/kubernetes-sigs/controller-tools/blob/895eccc97eb59b9973a8b610e6ed6a2fc5a5a6d3/go.mod).

/assign @caesarxuchao

### CODE REVIEW

**Comment by roycaihw** [comment]
/retest

```
GO111MODULE=on go test -mod=vendor ./pkg/...
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/fake	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/fake	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/internalinterfaces	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1	[no test files]
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1	[no test files]
ok  	sigs.k8s.io/kube-storage-version-migrator/pkg/controller	0.329s
ok  	sigs.k8s.io/kube-storage-version-migrator/pkg/initializer	0.023s
W1125 22:46:36.301213    6310 core.go:215] migration of pod51, in the namespace51 namespace, will be retried after a 1s delay: Timeout: retriable error
panic: test timed out after 10m0s

goroutine 38 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1618 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:167 +0x45

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0002a4600, 0x13f32c2, 0xb, 0x1493d70, 0x498001)
	/usr/local/go/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc000476900)
	/usr/local/go/src/testing/testing.go:1439 +0x78
testing.tRunner(0xc000476900, 0xc00017bde0)
	/usr/local/go/src/testing/testing.go:1123 +0xef
testing.runTests(0xc000449da0, 0x1d504e0, 0x3, 0x3, 0xbfe7d6291170fbff, 0x8bb392bfde, 0x1d62960, 0x40f5b0)
	/usr/local/go/src/testing/testing.go:1437 +0x2fe
testing.(*M).Run(0xc0000afb80, 0x0)
	/usr/local/go/src/testing/testing.go:1345 +0x1eb
main.main()
	_testmain.go:47 +0x138

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x1d62c00)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 51 [runnable]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedFieldNoCopy(0xc000412030, 0xc000782470, 0x2, 0x2, 0x1263660, 0xc000299880, 0x92e801, 0x0, 0x0)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go:61 +0xd7
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedString(0xc000412030, 0xc000782470, 0x2, 0x2, 0xc0002bb724, 0x6, 0x930801, 0x0, 0x0)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go:75 +0x67
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.getNestedString(0xc000412030, 0xc000782470, 0x2, 0x2, 0xc0002bb724, 0x6)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go:278 +0x49
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetName(0xc000590ab8, 0xc0002bb724, 0x6)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go:246 +0x85
k8s.io/client-go/testing.filterByNamespace.func1(0x1f, 0x1e, 0xc000590901)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/client-go/testing/fixture.go:487 +0x1f7
sort.insertionSort_func(0xc000782718, 0xc036469110, 0x1e, 0x25)
	/usr/local/go/src/sort/zfuncversion.go:12 +0xb4
sort.quickSort_func(0xc000782718, 0xc036469110, 0x1e, 0x25, 0xa)
	/usr/local/go/src/sort/zfuncversion.go:158 +0x1f6
sort.quickSort_func(0xc000782718, 0xc036469110, 0x4, 0x25, 0xa)
	/usr/local/go/src/sort/zfuncversion.go:148 +0x133
sort.quickSort_func(0xc000782718, 0xc036469110, 0x0, 0x64, 0xd)
	/usr/local/go/src/sort/zfuncversion.go:145 +0xf8
sort.Slice(0x12391e0, 0xc0461b09a0, 0xc000782718)
	/usr/local/go/src/sort/slice.go:17 +0xf3
k8s.io/client-go/testing.filterByNamespace(0xc0004c6330, 0x0, 0x0, 0xc00000c548, 0x1, 0xc036bce3f0, 0x8, 0x155eec0)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/client-go/testing/fixture.go:481 +0x309
k8s.io/client-go/testing.(*tracker).List(0xc00014c230, 0x0, 0x0, 0x13eeb6b, 0x2, 0x13ef61e, 0x5, 0x0, 0x0, 0x13eeb6b, ...)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/client-go/testing/fixture.go:252 +0x249
k8s.io/client-go/testing.ObjectReaction.func1(0x158fda0, 0xc0491f6900, 0x0, 0x1593700, 0x1d958c0, 0x15936a0, 0xc0461b0880)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/client-go/testing/fixture.go:89 +0xbc3
k8s.io/client-go/testing.(*SimpleReactor).React(0xc00059e060, 0x158fda0, 0xc0491f6900, 0x7f1062250101, 0xc0491f6840, 0x7f1062250108, 0x416d1b, 0xc0491f6840)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/client-go/testing/fixture.go:521 +0x3e
k8s.io/client-go/testing.(*Fake).Invokes(0xc000722be0, 0x158fda0, 0xc0491f6840, 0x1561340, 0xc0371423c0, 0x0, 0x0, 0x0, 0x0)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/client-go/testing/fake.go:141 +0x222
k8s.io/client-go/dynamic/fake.(*dynamicResourceClient).List(0xc0370e8d20, 0x1588820, 0xc000122018, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/vendor/k8s.io/client-go/dynamic/fake/simple.go:327 +0x395
sigs.k8s.io/kube-storage-version-migrator/pkg/migrator.(*migrator).list(0xc00022a3c0, 0x1588820, 0xc000122018, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/migrator/core.go:83 +0x115
sigs.k8s.io/kube-storage-version-migrator/pkg/migrator.(*migrator).Run(0xc00022a3c0, 0x1588820, 0xc000122018, 0x1, 0x1)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/migrator/core.go:93 +0x158
sigs.k8s.io/kube-storage-version-migrator/pkg/migrator.TestMetrics(0xc0002a4600)
	/home/prow/go/src/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/migrator/core_test.go:261 +0x26c
testing.tRunner(0xc0002a4600, 0x1493d70)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
FAIL	sigs.k8s.io/kube-storage-version-migrator/pkg/migrator	600.229s
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/migrator/metrics	[no test files]
ok  	sigs.k8s.io/kube-storage-version-migrator/pkg/trigger	8.770s
?   	sigs.k8s.io/kube-storage-version-migrator/pkg/version	[no test files]
FAIL
make: *** [Makefile:23: test] Error 1
```

**Comment by roycaihw** [comment]
The test timed out listing nodes: `item[0]: can't assign or convert unstructured.Unstructured into v1.Node`

Added a commit to remove the unnecessary `nodeList->unstructuredList` conversion (https://github.com/kubernetes-sigs/controller-runtime/issues/524#issuecomment-534555003 was the hint for the workaround)

**Comment by caesarxuchao** [comment]
I remember `klog/v1` and `klog/v2` doesn't work well together.

Can you double check if the storage migrator code indirectly imports `klog/v1` via `sigs.k8s.io/controller-tools`? E.g., if the relevant `sigs.k8s.io/controller-tools` code is only used to do code generation, then the migrator doesn't really uses `klog/v1`, then it's fine.

Otherwise we need to figure out the compatibility between `klog/v1` and `klog/v2`, and maybe we need to update `sigs.k8s.io/controller-tools` to use the `klog/v2`.

**Comment by roycaihw** [comment]
The migrator doesn't use klog/v1.

klog/v1 is not used by the main module:

```
$ go mod why k8s.io/klog
# k8s.io/klog
(main module does not need package k8s.io/klog)

$ go mod why k8s.io/klog/v2
# k8s.io/klog/v2
sigs.k8s.io/kube-storage-version-migrator/cmd/initializer
k8s.io/klog/v2
```

klog/v1 is used by `v0.18.2` k8s packages and konnectivity-client@v0.0.7, which are used by `sigs.k8s.io/controller-tools@v0.4.1`, not by the storage migrator.

```
$ go mod graph > graph

$ grep k8s.io\/klog.*v1 graph
k8s.io/apimachinery@v0.18.2 k8s.io/klog@v1.0.0
k8s.io/apiserver@v0.18.2 k8s.io/klog@v1.0.0
k8s.io/component-base@v0.18.2 k8s.io/klog@v1.0.0
k8s.io/code-generator@v0.18.2 k8s.io/klog@v1.0.0
k8s.io/client-go@v0.18.2 k8s.io/klog@v1.0.0
k8s.io/klog@v1.0.0 github.com/go-logr/logr@v0.1.0
k8s.io/apiextensions-apiserver@v0.18.2 k8s.io/klog@v1.0.0
sigs.k8s.io/apiserver-network-proxy/konnectivity-client@v0.0.7 k8s.io/klog@v1.0.0

$ grep "@v0.18.2$" graph
k8s.io/api@v0.18.2 k8s.io/apimachinery@v0.18.2
k8s.io/apiserver@v0.18.2 k8s.io/component-base@v0.18.2
k8s.io/apiserver@v0.18.2 k8s.io/client-go@v0.18.2
k8s.io/apiserver@v0.18.2 k8s.io/apimachinery@v0.18.2
k8s.io/apiserver@v0.18.2 k8s.io/api@v0.18.2
k8s.io/component-base@v0.18.2 k8s.io/client-go@v0.18.2
k8s.io/component-base@v0.18.2 k8s.io/apimachinery@v0.18.2
k8s.io/apiextensions-apiserver@v0.18.2 k8s.io/component-base@v0.18.2
k8s.io/apiextensions-apiserver@v0.18.2 k8s.io/api@v0.18.2
k8s.io/apiextensions-apiserver@v0.18.2 k8s.io/apimachinery@v0.18.2
k8s.io/apiextensions-apiserver@v0.18.2 k8s.io/apiserver@v0.18.2
k8s.io/apiextensions-apiserver@v0.18.2 k8s.io/client-go@v0.18.2
k8s.io/client-go@v0.18.2 k8s.io/apimachinery@v0.18.2
k8s.io/client-go@v0.18.2 k8s.io/api@v0.18.2
k8s.io/apiextensions-apiserver@v0.18.2 k8s.io/code-generator@v0.18.2
sigs.k8s.io/controller-tools@v0.4.1 k8s.io/apimachinery@v0.18.2
sigs.k8s.io/controller-tools@v0.4.1 k8s.io/apiextensions-apiserver@v0.18.2
sigs.k8s.io/controller-tools@v0.4.1 k8s.io/api@v0.18.2

$ grep "konnectivity-client@v0.0.7$" graph
k8s.io/apiserver@v0.18.2 sigs.k8s.io/apiserver-network-proxy/konnectivity-client@v0.0.7
```

**Comment by roycaihw** [comment]
The test failure is unrelated. It's a new optional prow job that we added recently.

**Pull request merged**
